name: 'Nissuer'
description: 'A GitHub Action for tried and tired maintainers.'
author: 'Balázs Orbán'
branding:
  icon: check-square
  color: orange

inputs:
  reproduction-comment:
    description: 'Either a string or a path to a .md file inside the repository. Example: ".github/invalid-reproduction.md"'
    default: '.github/invalid-reproduction.md'
  reproduction-hosts:
    description: 'Comma-separated list of hostnames that are allowed for reproductions. Example: "github.com,codesandbox.io"'
    default: github.com
  reproduction-invalid-label:
    description: 'Label to apply to issues without a valid reproduction. Example: "invalid-reproduction"'
    default: 'invalid-reproduction'
  reproduction-link-section:
    description: 'A regular expression string with "(.*)" matching a valid URL in the issue body. The result is trimmed. Example: "### Link to reproduction(.*)### To reproduce"'
    default: '### Link to reproduction(.*)### To reproduce'
  label-comments:
    description: 'Autocomment on issues based on the added label. It should be a JSON object, where the key is a label, and the value is a file path or a comment text. Example: {"invalid": ".github/invalid-reproduction.md"}'
    default: '{}'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run action
      run: node ${{ github.action_path }}/dist/index.js
      shell: sh