name: 'Nissuer'
description: 'A GitHub Action for tried and tired maintainers.'
author: 'Balázs Orbán'
branding:
  icon: check-square
  color: orange

inputs:
  comment-unhelpful-weight:
    description: 'If an issue comment is below this rate, it will be marked as off-topic and gets hidden. Example: 0.3'
    default: '0.3'
  reproduction-comment:
    description: 'Either a string or a path to a .md file inside the repository. Example: ".github/invalid-reproduction.md"'
    default: '.github/invalid-reproduction.md'
  reproduction-hosts:
    description: 'Comma-separated list of hostnames that are allowed for reproductions. Example: "github.com,codesandbox.io"'
    default: github.com
  reproduction-invalid-label:
    description: 'Label to apply to issues without a valid reproduction. Example: "invalid-reproduction"'
    default: 'invalid-reproduction'
  reproduction-issue-labels:
    description: 'Comma-separated list of issue labels. If configured, only verify reproduction URLs of issues with one of these labels present. Example: "bug"'
    default: ''
  reproduction-link-section:
    description: 'A regular expression string with "(.*)" matching a valid URL in the issue body. The result is trimmed. Example: "### Link to reproduction(.*)### To reproduce"'
    default: '### Link to reproduction(.*)### To reproduce'
  label-comments:
    description: 'Autocomment on issues based on the added label. It should be a JSON object, where the key is a label, and the value is a file path or a comment text. Example: {"invalid reproduction": ".github/invalid-reproduction.md"}'
    default: '{"invalid reproduction": ".github/invalid-reproduction.md"}'
  label-area-prefix:
    description: 'Only look for these labels when autolabeling based on the user selection. Example: "area:"'
    default: 'area:'
  label-area-section:
    description: 'A regular expression string with "(.*)" matching a section in the issue body to look for user selected areas. The result is trimmed. Example: "### Which area(s) are affected?(.*)### Additional context"'
  webhook-url:
    description: 'Webhook URL to send notifications to. Example: "https://example.com/api/webhooks/nissuer"'
    default: ''
  webhook-secret:
    description: 'Secret to use for the webhook.'
    default: ''
  delete-vulnerability-report:
    description: 'Delete the vulnerability report after sending it to the webhook. Example: "false"'
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/checkout@v4
    - name: Run action
      run: node ${{ github.action_path }}/dist/index.js
      shell: sh
      # https://github.com/actions/runner/issues/665#issuecomment-676581170
      env:
        "INPUT_REPRODUCTION_COMMENT": ${{inputs.reproduction-comment}}
        "INPUT_REPRODUCTION_HOSTS": ${{inputs.reproduction-hosts}}
        "INPUT_REPRODUCTION_INVALID_LABEL": ${{inputs.reproduction-invalid-label}}
        "INPUT_REPRODUCTION_ISSUE_LABELS": ${{inputs.reproduction-issue-labels}}
        "INPUT_REPRODUCTION_LINK_SECTION": ${{inputs.reproduction-link-section}}
        "INPUT_LABEL_COMMENTS": ${{inputs.label-comments}}
        "INPUT_COMMENT_UNHELPFUL_WEIGHT": ${{inputs.comment-unhelpful-weight}}
        "INPUT_LABEL_AREA_PREFIX": ${{inputs.label-area-prefix}}
        "INPUT_LABEL_AREA_SECTION": ${{inputs.label-area-section}}
        "INPUT_WEBHOOK_URL": ${{inputs.webhook-url}}
        "INPUT_WEBHOOK_SECRET": ${{inputs.webhook-secret}}
        "INPUT_DELETE_VULNERABILITY_REPORT": ${{inputs.delete-vulnerability-report}}
