name: Nissuer test

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Nissuer
        uses: balazsorban44/nissuer@1.1.1
        with:
          label-comments: '{"incomplete": ".github/invalid-reproduction.md"}'
