name: Nissuer test

on:
  issues:
    types: [opened, labeled, edited]
  issue_comment:
    types: [created, edited]

permissions:
  issues: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Nissuer
        uses: balazsorban44/nissuer@1.9.1
        with:
          label-area-section: 'Which area\(s\) are affected\?(.*)'
          reproduction-issue-labels: "bug,"
